### ISSUE TITLE
Download SIA (Produção Ambulatorial) data besides São Paulo

### ISSUE THREAD

**Issue by phcm-pedro** [AlertaDengue/PySUS#133]
I'm trying download data SIA (Produção Ambulatorial) of other states, like RJ, BA, etc, but, I'm having this problem:
Code:
pa = download('RJ',2020,12,group='PA')[0]
pa = parquets_to_dataframe(pa)
pa.head()
Error:
AttributeError: 'NoneType' object has no attribute 'head'

![image](https://github.com/AlertaDengue/PySUS/assets/134331672/57833ab6-290d-45d4-a3de-c4fe18beaa16)

**Comment by fccoelho** [comment]
@luabida could you validate this?

**Comment by luabida** [comment]
The only problem I can see here is that the SIA datasets are quite big and it takes very long to download and a lot of memory when loaded. I was able of downloading the parquets from RJ with:

```python
pa = download('RJ', 2020, 12, group='PA')
```

without `[0]` because RJ's dataset is not split in multiple files and fetches a big'o dbc into parquets:

```py
import os
os.listdir(pa)
```

<details>
['e23f654e7e6542dababff80935dad23e-0.parquet',
 '5c5065789b534e8f89a8bc9a194544e0-0.parquet',
 '13f8e99f19c04326872140d97b5a56a6-0.parquet',
 'e9d4e93c17724fc198c467330b5cd4ef-0.parquet',
 '12d7f0b91be84fa1b2dc2756dea779d8-0.parquet',
 '1ffa9fe61d2b490ab9bce0f1815e4d6a-0.parquet',
 '967e7ff1687f4124a66dcf1c10fe22d6-0.parquet',
 '75ae20d30bea4630a948bb48c211ec84-0.parquet',
 'aebb37c09a1547a3b02aee46144da8bf-0.parquet',
 'b550e6b840524788b0d87d94b04867a2-0.parquet',
 '1c165e7f519243a6bb63b033def4d0ac-0.parquet',
 '0a59a806b953478ba93959cdac66f282-0.parquet',
 '29b3a26146b64147a76829b66e8b410e-0.parquet',
 '6e780c6a8dda44b49cd09dddf70a2652-0.parquet',
 'fe7b2d6f7ff343bcb9c5ef6eb0aa5d23-0.parquet',
 'e0ac546c5a40445ca3ff53a0541a5400-0.parquet',
 '327b43acc25f4ea980c16dc8c1f4cf99-0.parquet',
 '974b38472ced43eeaebde9d70b4d1ae0-0.parquet',
 'c3875be3539e42ce88242548ae6769ad-0.parquet',
 'ca9c313072264bed8f14fd793e4ab50e-0.parquet',
 'cd2af2e5d423441ca04f72fe7bf9f07c-0.parquet',
 '0e8425bb83034b94add3b5071b7f1bc5-0.parquet',
 '9cef3f916ed74d8f92392374b1c41bc8-0.parquet',
 '6c80cec01667436bbc1777d979477bda-0.parquet',
 '09cc127ddfb64bdf908dcb5dec1f9ca4-0.parquet',
 '5bbc7a19915c4ca3bacd14d36a4b5987-0.parquet',
 'e96c3aa781d44f3fbdd0be750f474ba2-0.parquet',
 'e909c69543804905b406317b21ad124a-0.parquet',
 '23c83a509d084e8589bb682e59353fde-0.parquet',
 'a4457362d33c4726a329146b9a710378-0.parquet',
 '91c9ad6bc1724d3c8d703dfa0865979f-0.parquet',
 '11d23d29a79f4085ba977f8027ff9c71-0.parquet',
 '549f816f2aca44e697c7eef5002e9086-0.parquet',
 'ca702a8636af4a65afdc7ef936c1c3ac-0.parquet',
 '4dd3a6ddaa7d4cbd854cb9690565e2ab-0.parquet',
 'efe6469a54f94a169f719fd974a63f62-0.parquet',
 '9055a0c44792427a9aecbb20a335d6a0-0.parquet',
 '3de156cc219f4fcaacfbe2502d9c8812-0.parquet',
 '0a90670d545e4864b15566aac86a418d-0.parquet',
 '6d4ba94df59b48a8a949552c0e4bc001-0.parquet',
 '851eda9903664b24a32862fc55a2078f-0.parquet',
 '539208d0b8c5466a8c6452f7c8bf7434-0.parquet',
 'bff740234af341ff938a2073b09c043c-0.parquet',
 '1a266573126445be9e41fe4feafcd185-0.parquet',
 'e702f866a1dd4c2ba68742f983917878-0.parquet',
 '05c8e01248384954a4aa635ae0b19856-0.parquet',
 'a13a4415a0c349319f8938858628a5ea-0.parquet',
 '3d9e6cacad6a4a07831f5eb101a487d7-0.parquet',
 'f7fba6e9b8d1466fb85ee67c728831ee-0.parquet',
 'c9c256d5e33a4a2c874fbc604f25eac1-0.parquet',
 'bbebc2cb9f274b348c6b052240269255-0.parquet',
 'e71adc71468c42bf90f6720fcbf2d796-0.parquet',
 '09a5c59169724f48bfdedaf2705911de-0.parquet',
 '3d02432185e148e4a8d646875518ae05-0.parquet',
 '38ccfdb1052e4616801e334e9ef1feb8-0.parquet',
 '4e8b741e3fb44a96ad8239a8f6728a2b-0.parquet',
 'ab0d24b3052747b49b19367cd6df5060-0.parquet',
 '5a69f75ba4d149799edd4195adbdfd06-0.parquet',
 '99146b1096f74b85b2e196066d85fce5-0.parquet',
 '1d8858d0803f4e31b6ebce41af34a231-0.parquet',
 '70e8317b5f6d42ab922e607d2f462c2b-0.parquet',
 '9958001411e240e3b19dcc105e9fd1b0-0.parquet',
 'fc1388efa309478385a44b2d857f06e6-0.parquet',
 '4fe819a2adc346efbfbf11ffb755a837-0.parquet',
 'e1fe3ec100b045b7a5203c11f71f4681-0.parquet',
 'f6884916143c476c819189fd50568f5b-0.parquet',
 '736d4d7613344aa5ac0b8128530e7b42-0.parquet',
 '2a48afd22e5f41e49cc68f53582e19ec-0.parquet',
 '471d3df3b8c94e6f9ebed0b7aeb050c4-0.parquet',
 'cc36d74e8e874bb489e9eecea36b4b0b-0.parquet',
 '109f3b60e9834ad29dd93e92d950831d-0.parquet',
 '82520962fde440f2a8da01858c658653-0.parquet',
 '99d3f2aff70440129d37cb6d8c0ad5ca-0.parquet',
 'eabfbfbc96b4489e8319c23c7926e67f-0.parquet',
 '5a1d54a32d3443b0808e3828286916ae-0.parquet',
 '2f49d535e2db4547b485e14e4638103b-0.parquet',
 '1bfa0869062b413d85fe6ce4a0d6c3a7-0.parquet',
 '446fdc6c68ec4ca5b2f48e103eec286b-0.parquet',
 '1a450615194c442ea6702034a55bdf79-0.parquet',
 '8fcce077034442128973e47f5974c347-0.parquet']
</details>

**Comment by fccoelho** [comment]
@phcm-pedro does that solve your issue?

**Comment by augusto-herrmann** [comment]
I have also tried downloading the datasets using PySUS 0.6.0 and have been getting errors:

```python
from pysus.online_data.SIA import download

bi = download('DF', 2020, 12, group='BI')
```
```
No such file or directory
unpack requires a buffer of 32 bytes
```


I have checked the FTP directory and have found the file at `ftp://ftp.datasus.gov.br/dissemin/publicos/SIASUS/200801_/Dados/BIDF2012.dbc`. It's not even that large, with just 9,0 MB.

This is just an example, as many other datasets and states do give a very similar error.

**Comment by augusto-herrmann** [comment]
I just realize that I have been using an old PySUS version, the current one is 0.9.3.

The strange thing is that even if I create a new Python virtual environment just for this, or upgrade with `pip install -U pysus`, the new version does not appear. Even if I do `pip install -U pip` and then `pip install -U pysus==0.9.3`, it says it cannot find that version, and then displays a list of versions available that go only up to 0.6.0. I have am an experienced Python developer and had up until now not found this problem in any other Python package. :thinking: Maybe I should open another issue just for discussing this.

I only realized that I had been using an ancient PySUS version after I had already started debugging with `ipdb` and found that the lines of code mentioned there did not exist in current code.

**Comment by gabrielfmcoelho** [comment]
@augusto-herrmann, recently I have been working on an ETL with data from datasus (especially cnes), and I simply can't do anything!

I have used read_dbc to read SIH, and great!
But when i try to read cnes datasets, nothing reads it! read_dbc, pysus, and others.

Example:
`from pysus.online_data.CNES import download
groups = ['LT', 'ST', 'DC' , 'SR', 'PF', 'EP']
state = "PI"
years = [2022, 2023]
months = [1,2,3,4,5,6,7,8,9,10,11,12]

for group in groups:
    df = download(group, state, years, months)
    print(df)
`

`('/home/coelho/pysus/LTPI2201.parquet', '/home/coelho/pysus/LTPI2202.parquet', '/home/coelho/pysus/LTPI2203.parquet', '/home/coelho/pysus/LTPI2204.parquet', '/home/coelho/pysus/LTPI2205.parquet', '/home/coelho/pysus/LTPI2206.parquet', '/home/coelho/pysus/LTPI2207.parquet', '/home/coelho/pysus/LTPI2208.parquet', '/home/coelho/pysus/LTPI2209.parquet', '/home/coelho/pysus/LTPI2210.parquet', '/home/coelho/pysus/LTPI2211.parquet', '/home/coelho/pysus/LTPI2212.parquet', '/home/coelho/pysus/LTPI2301.parquet', '/home/coelho/pysus/LTPI2302.parquet', '/home/coelho/pysus/LTPI2303.parquet', '/home/coelho/pysus/LTPI2304.parquet', '/home/coelho/pysus/LTPI2305.parquet', '/home/coelho/pysus/LTPI2306.parquet', '/home/coelho/pysus/LTPI2307.parquet')
Traceback (most recent call last):
  File "/mnt/c/Users/gcmas/OneDrive/Área de Trabalho/S3 Biotech/Desenvolvimento/ETL Growth/CNES/Data/Temp/test.py", line 8, in <module>
    df = download(group, state, years, months)
  File "/usr/local/lib/python3.10/dist-packages/pysus/online_data/CNES.py", line 50, in download
    return FTP_Downloader('CNES').download(
  File "/usr/local/lib/python3.10/dist-packages/pysus/online_data/__init__.py", line 430, in download
    parquet_dir = self._dbfc_to_parquets(
  File "/usr/local/lib/python3.10/dist-packages/pysus/online_data/__init__.py", line 585, in _dbfc_to_parquets
    for d in self._stream_DBF(DBF(fpath, encoding='iso-8859-1', raw=True)):
  File "/usr/local/lib/python3.10/dist-packages/dbfread-2.0.7-py3.10.egg/dbfread/dbf.py", line 122, in __init__
    self._read_field_headers(infile)
  File "/usr/local/lib/python3.10/dist-packages/dbfread-2.0.7-py3.10.egg/dbfread/dbf.py", line 224, in _read_field_headers
    field = DBFField.unpack(sep + infile.read(DBFField.size - 1))
  File "/usr/local/lib/python3.10/dist-packages/dbfread-2.0.7-py3.10.egg/dbfread/struct_parser.py", line 36, in unpack
    items = zip(self.names, self.struct.unpack(data))
struct.error: unpack requires a buffer of 32 bytes`

Can someone help me with the error? I am using python 3.10.12, with pysus 0.9.4 with wsl2 - ubuntu alongside my win 11

**Comment by gabrielfmcoelho** [comment]
@augusto-herrmann, recently I have been working on an ETL with data from datasus (especially cnes), and I simply can't do anything!

I have used read_dbc to read SIH, and great!
But when i try to read cnes datasets, nothing reads it! read_dbc, pysus, and others.

Example:
```python
from pysus.online_data.CNES import download
groups = ['LT', 'ST', 'DC' , 'SR', 'PF', 'EP']
state = "PI"
years = [2022, 2023]
months = [1,2,3,4,5,6,7,8,9,10,11,12]

for group in groups:
    df = download(group, state, years, months)
    print(df)
``` 

```Shell
('/home/coelho/pysus/LTPI2201.parquet', '/home/coelho/pysus/LTPI2202.parquet', '/home/coelho/pysus/LTPI2203.parquet', '/home/coelho/pysus/LTPI2204.parquet', '/home/coelho/pysus/LTPI2205.parquet', '/home/coelho/pysus/LTPI2206.parquet', '/home/coelho/pysus/LTPI2207.parquet', '/home/coelho/pysus/LTPI2208.parquet', '/home/coelho/pysus/LTPI2209.parquet', '/home/coelho/pysus/LTPI2210.parquet', '/home/coelho/pysus/LTPI2211.parquet', '/home/coelho/pysus/LTPI2212.parquet', '/home/coelho/pysus/LTPI2301.parquet', '/home/coelho/pysus/LTPI2302.parquet', '/home/coelho/pysus/LTPI2303.parquet', '/home/coelho/pysus/LTPI2304.parquet', '/home/coelho/pysus/LTPI2305.parquet', '/home/coelho/pysus/LTPI2306.parquet', '/home/coelho/pysus/LTPI2307.parquet')
Traceback (most recent call last):
  File "/mnt/c/Users/gcmas/OneDrive/Área de Trabalho/S3 Biotech/Desenvolvimento/ETL Growth/CNES/Data/Temp/test.py", line 8, in <module>
    df = download(group, state, years, months)
  File "/usr/local/lib/python3.10/dist-packages/pysus/online_data/CNES.py", line 50, in download
    return FTP_Downloader('CNES').download(
  File "/usr/local/lib/python3.10/dist-packages/pysus/online_data/__init__.py", line 430, in download
    parquet_dir = self._dbfc_to_parquets(
  File "/usr/local/lib/python3.10/dist-packages/pysus/online_data/__init__.py", line 585, in _dbfc_to_parquets
    for d in self._stream_DBF(DBF(fpath, encoding='iso-8859-1', raw=True)):
  File "/usr/local/lib/python3.10/dist-packages/dbfread-2.0.7-py3.10.egg/dbfread/dbf.py", line 122, in __init__
    self._read_field_headers(infile)
  File "/usr/local/lib/python3.10/dist-packages/dbfread-2.0.7-py3.10.egg/dbfread/dbf.py", line 224, in _read_field_headers
    field = DBFField.unpack(sep + infile.read(DBFField.size - 1))
  File "/usr/local/lib/python3.10/dist-packages/dbfread-2.0.7-py3.10.egg/dbfread/struct_parser.py", line 36, in unpack
    items = zip(self.names, self.struct.unpack(data))
struct.error: unpack requires a buffer of 32 bytes
``` 

Can someone help me with the error? I am using python 3.10.12, with pysus 0.9.4 with wsl2 - ubuntu alongside my win 11

**Comment by fccoelho** [comment]
@gabrielfmcoelho apparently the problem only happens on the "ST" files. If you remove ST from your groups list, the download proceeds normally.

One other aspect is that the error is arising from the dbfread package, not from PySUS code.
This may be caused by files using old windows encoding(CP1252): https://groups.google.com/g/python-dbase/c/JOpbNHjCg-I?pli=1

There is an open issue about this on Dbfread since 2018.

PySUS actually manages to extract the DBC to DBF but the DBFs are corrupted somehow. You can see the DBF for the first month in the PySUS folder. I tried opening it directly with other encodings, or even with LibreOffice, but without success. My guess is that these files are corrupted at the source.

**Comment by gabrielfmcoelho** [comment]
Thanks for answering me @fccoelho, and btw you have a magnificent project. 
_(I'm still within an intermediate level skill with python, but would love to help contribute in anyway possible)_
I understood it, thank you.
But I think its a shame, cuz its possible to read it, but only the R version of read.dbc manage to do it.

Honestly, I'm not a fan of R, but managed to create the pipeline by using python subprocess to call a R script

**Comment by fccoelho** [comment]
Thanks @gabrielfmcoelho. We welcome contributors from all skill levels, If you see something on our issue list , feel free to open a PR! :-)

I am re-opening this issue, because if R is able to open these DBCs, then they may not be corrupted after all.
 ping @luabida

**Comment by gabrielfmcoelho** [comment]
@fccoelho, i'm sure they are not corrupted cuz i can open then with R read_dbc transform into csv, and load on a python dataframe normally. What do u think about this temporary approach to mix python and R to bypass the problem?

**Comment by fccoelho** [comment]
For now, it can be a workaround, but we will check why our readdbc code is failing  only in these files.
