### ISSUE TITLE
Pandas does not concatenate the parquet files

### ISSUE THREAD

**Issue by esloch** [AlertaDengue/PySUS#92]
Unable to concatenate parquet files to dataframe.
> disease dengue 
> year 2020  

https://github.com/AlertaDengue/PySUS/blob/master/pysus/tests/test_data/test_sinan.py#L43
```  
48 DENGBR20.parquet/6d35585c41984b459cc3f72986f9aa6c-0.parquet
49 DENGBR20.parquet/f1d9168f79e1431a933faa433859c305-0.parquet
50 DENGBR20.parquet/5d8a203ccca04e87b12c5ef465a4d32d-0.parquet
Killed
pysus/tests/test_data/test_sinan.py::TestSINANDownload::test_chunked_df_size Killed
``` 
Reproduce the error:
``` 
fn = download(2020, "dengue", return_fname=True)
for i, f in enumerate(glob(f"{fn}/*.parquet")):
    if i == 0:
        df2 = pd.read_parquet(f)
    else:
        df2 = pd.concat([df2, pd.read_parquet(f)], ignore_index=True)
   ```

**Comment by fccoelho** [comment]
This is possiblly due to the concat process filling up the memory before completing the concatenation.
the solution here is to load only one or two columns from the parquets in the test.

**Comment by fccoelho** [comment]
I have just ran this block of code  and the total size of dengue 2020 was just 42M (is that right? apparently yes, because parquet files are compressed)
![image](https://user-images.githubusercontent.com/140123/188496533-346f7273-2054-472a-b534-6234c92f8180.png)
so it was possible to concatenate the whole set of parquet files in memory:

![image](https://user-images.githubusercontent.com/140123/188496805-d5793dbf-a3ee-48fa-9e82-4c6b48f3af6e.png)

Apparently the size of the dataset is correct, if we do a rough comparison with the contents of the FTP:
![image](https://user-images.githubusercontent.com/140123/188496975-fec18eb0-f93a-4231-89b2-d486470dd711.png)

so maybe this issue is not an issue after all? what do you say @esloch?

**Comment by esloch** [comment]
> so maybe this issue is not an issue after all? what do you say @esloch? 

I couldn't identify the error, PANDAS reloaded the parquetfiles correctly.
